### ISSUE TITLE
could not find function "expect_match"

### ISSUE THREAD

**Issue by aadler** [markvanderloo/tinytest#124]
I am in the process of switching some old `expect_true(grepl(foo, bar, fixed = TRUE))` to `expect_match(bar, foo, fixed = TRUE)` and I'm getting `could not find function "expect_match"` errors when checking my package. However, running the code from the prompt works properly. This doesn't apply to any other commands like `expect_equal`, `expect_false`, etc. I have ensured that the RStudio IDE does **not** use `devtools` package functions. Any thoughts?

**Comment by markvanderloo** [comment]
Yes, this is fixed. I'm in the process of uploading to CRAN but I got some conflicts with Importing packages. Looking into it.

**Comment by LiNk-NY** [comment]
Hi Mark! @markvanderloo 

Has this been uploaded to CRAN? 
I still get this error message with `tinytest_1.4.1.tar.gz` : 

See the GitHub Action run here: 
https://github.com/r-universe/link-ny/actions/runs/9103419708/job/25025326681#step:4:565

**Comment by LiNk-NY** [comment]
**Update**: For now, I am using `tinytest::expect_match` in the `test_*.R` file.

**Comment by aadler** [comment]
> **Update**: For now, I am using `tinytest::expect_match` in the `test_*.R` file.

I've stuck with the `expect_true(grepl(foo, bar, fixed = TRUE))` format for now. This allows me to do more sophistcated checks such as:
```r
# Test that CITATION doesn't contain the name of any other of my packages
expect_false(any(sapply(myOtherPkgs, grepl,
                       x = toBibtex(citation("MBBEFDLite"), fixed = TRUE))))
```

in https://github.com/aadler/MBBEFDLite/blob/master/inst/tinytest/test_package_metadata.R.
